-- Synthetic fixtures remain inside this transaction; ROLLBACK leaves the public site untouched.
begin;
create temporary table verification_results(name text,passed boolean);
do $$ declare u uuid:=gen_random_uuid(); g uuid; c uuid; st uuid; a uuid; p uuid; payload jsonb; response jsonb; req uuid:=gen_random_uuid(); caught boolean; begin
 insert into auth.users(id,email) values(u,'vegas-quant-test@example.invalid');
 insert into private.admin_users(user_id) values(u);
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 insert into public.games(slug,away_team,home_team,kickoff,venue,slot) values('synthetic-test-'||u,'Synthetic A','Synthetic B',now()+interval '1 hour','Test only','Test only') returning id into g;
 insert into public.challenges(status) values('ANALYSIS IN PROGRESS') returning id into c;
 insert into public.challenge_stages(challenge_id,stage_number,slot,game_id,status) values(c,1,'Test only',g,'ANALYSIS IN PROGRESS') returning id into st;
 response=private.publish('analysis',jsonb_build_object('game_id',g,'title','SYNTHETIC TEST ONLY','raw_handoff','Synthetic test fixture; not an analyst recommendation.','sections','{}'::jsonb),gen_random_uuid()); a=(response->>'id')::uuid;
 payload=jsonb_build_object('game_id',g,'stage_id',st,'analysis_id',a,'market','Side','selection','Synthetic fixture','recommended_line',3,'odds',-110,'stake_cents',2000,'model_probability',56,'market_probability',52.4,'edge',2.99,'confidence',7,'risk',5,'predicted_close','Test','best_number','Test','bet_grade','B','fear_index',7,'timing','Test','why_like','Test','why_lose','Test','playable_number','Test','pass_number','Test','book','Test','raw_handoff','Synthetic test only');
 caught=false; begin perform private.publish('pick',payload,gen_random_uuid()); exception when check_violation then caught=true; end;
 if not caught then raise exception 'FAIL: below-threshold pick accepted'; end if;
 insert into verification_results values('Sub-3% official pick rejected',true);
 perform private.publish('pause',jsonb_build_object('challenge_id',c,'reason','Synthetic insufficient edge'),gen_random_uuid());
 if (select current_stage from public.challenges where id=c)<>1 or (select balance_cents from public.challenges where id=c)<>2000 then raise exception 'FAIL: pass advanced or changed bankroll'; end if;
 insert into verification_results values('Pass pauses without advancing or spending',true);
 payload=jsonb_set(payload,'{edge}','3.6');
 caught=false; begin perform private.publish('pick',payload,gen_random_uuid()); exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: paused challenge accepted pick'; end if;
 insert into verification_results values('Paused challenge blocks publication',true);
 perform private.publish('resume',jsonb_build_object('challenge_id',c,'next_stage',1,'reason','Synthetic explicit resume'),gen_random_uuid());
 caught=false; begin perform private.publish('pick',jsonb_set(payload,'{stake_cents}','2001'),gen_random_uuid()); exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: overdraft accepted'; end if;
 insert into verification_results values('Stake above bankroll rejected',true);
 response=private.publish('pick',payload,req); p=(response->>'id')::uuid;
 if private.publish('pick',payload,req)<>response then raise exception 'FAIL: idempotency'; end if;
 insert into verification_results values('Retry returns same pick without duplicate stake',true);
 caught=false; begin update public.official_picks set recommended_line=7 where id=p; exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: recommendation changed'; end if;
 caught=false; begin delete from public.analysis_versions where id=a; exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: analysis deleted'; end if;
 insert into verification_results values('Original picks and analysis immutable',true);
 caught=false; begin perform private.publish('result',jsonb_build_object('pick_id',p,'result','WIN','away_score',10,'home_score',20,'source','Test'),gen_random_uuid()); exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: settled before kickoff'; end if;
 insert into verification_results values('Premature settlement rejected',true);
 perform private.publish('entry',jsonb_build_object('pick_id',p,'line',3,'odds',-110,'source','Test','bet_at',now()),gen_random_uuid());
 -- Advance only the synthetic fixture to simulate completion, inside the rollback transaction.
 update public.games set kickoff=now()-interval '2 hours' where id=g;
 perform private.publish('close',jsonb_build_object('pick_id',p,'line',2.5,'odds',-110,'source','Test','observed_at',now()-interval '2 hours'),gen_random_uuid());
 perform private.publish('result',jsonb_build_object('pick_id',p,'result','WIN','away_score',10,'home_score',20,'source','Test'),gen_random_uuid());
 if (select balance_cents from public.challenges where id=c)<>3818 then raise exception 'FAIL: expected $38.18'; end if;
 insert into verification_results values('Win uses actual -110 entry and rounds to $38.18',true);
 caught=false; begin perform private.publish('result',jsonb_build_object('pick_id',p,'result','WIN','away_score',10,'home_score',20,'source','Test'),gen_random_uuid()); exception when unique_violation then caught=true; end;
 if not caught then raise exception 'FAIL: duplicate settlement'; end if;
 if (select balance_cents from public.challenges where id=c)<>3818 then raise exception 'FAIL: double counted'; end if;
 insert into verification_results values('Duplicate result cannot double-count bankroll',true);
 perform set_config('request.jwt.claim.sub','',true);
 perform set_config('request.jwt.claims','{}',true);
 caught=false; begin perform private.publish('pause',jsonb_build_object('challenge_id',c,'reason','Test'),gen_random_uuid()); exception when raise_exception then caught=true; end;
 if not caught then raise exception 'FAIL: unapproved publish'; end if;
 insert into verification_results values('Unapproved account cannot publish',true);
end $$;
select * from verification_results;
rollback;
